spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway: # telling gateway to connect with discovery server(eureka) and locate all details about microservices
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false

      #data:
   # redis:
     # connect-timeout: 2s
     # host: localhost
    #  port: 6379
     # timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Bank Gateway Server Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      burak:
        gatewayserver: DEBUG
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 #make 10 requests to accounts ms
      permittedNumberOfCallsInHalfOpenState: #make 2 request to accounts ms on half-open state
      failureRateThreshold: 50 #if at least %50 requests fail, move to open state from closed state
      waitDurationInOpenState: 10000
